// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tip4Gen.Infrastructure.Persistence;

#nullable disable

namespace Tip4Gen.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525213027_AddLongTermTips")]
    partial class AddLongTermTips
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tip4Gen.Domain.Tipping.LongTermTip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("TargetPlayerName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("target_player_name");

                    b.Property<Guid?>("TargetTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_team_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TargetTeamId");

                    b.HasIndex("UserId", "Type")
                        .IsUnique();

                    b.ToTable("long_term_tips", null, t =>
                        {
                            t.HasCheckConstraint("ck_long_term_tips_target_shape", "(type = 'Winner' AND target_team_id IS NOT NULL AND target_player_name IS NULL) OR (type = 'TopScorer' AND target_player_name IS NOT NULL AND target_team_id IS NULL)");

                            t.HasCheckConstraint("ck_long_term_tips_type", "type IN ('Winner','TopScorer')");
                        });
                });

            modelBuilder.Entity("Tip4Gen.Domain.Tipping.Tip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AwayGoals")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals");

                    b.Property<int>("HomeGoals")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals");

                    b.Property<bool>("Joker")
                        .HasColumnType("boolean")
                        .HasColumnName("joker");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("UserId", "Joker")
                        .HasFilter("joker = TRUE");

                    b.HasIndex("UserId", "MatchId")
                        .IsUnique();

                    b.ToTable("tips", null, t =>
                        {
                            t.HasCheckConstraint("ck_tips_away_goals_range", "away_goals >= 0 AND away_goals <= 15");

                            t.HasCheckConstraint("ck_tips_home_goals_range", "home_goals >= 0 AND home_goals <= 15");
                        });
                });

            modelBuilder.Entity("Tip4Gen.Domain.Tournaments.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AwayGoals")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("away_team_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("external_id");

                    b.Property<string>("GroupCode")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("group_code");

                    b.Property<int?>("HomeGoals")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_team_id");

                    b.Property<DateTimeOffset>("KickoffUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kickoff_utc");

                    b.Property<string>("RoundLabel")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("round_label");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("stage");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("KickoffUtc");

                    b.HasIndex("Status");

                    b.HasIndex("TournamentId", "ExternalId")
                        .IsUnique();

                    b.ToTable("matches", null, t =>
                        {
                            t.HasCheckConstraint("ck_matches_score_nullability", "(home_goals IS NULL) = (away_goals IS NULL)");

                            t.HasCheckConstraint("ck_matches_stage", "stage IN ('Group','R32','R16','QF','SF','Bronze','Final')");

                            t.HasCheckConstraint("ck_matches_status", "status IN ('Scheduled','Live','Finished','Postponed','Cancelled','Abandoned','Awarded')");

                            t.HasCheckConstraint("ck_matches_teams_distinct", "home_team_id <> away_team_id");
                        });
                });

            modelBuilder.Entity("Tip4Gen.Domain.Tournaments.NationalTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("external_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("teams_national", (string)null);
                });

            modelBuilder.Entity("Tip4Gen.Domain.Tournaments.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<string>("ExternalLeagueId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("external_league_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Season")
                        .HasColumnType("integer")
                        .HasColumnName("season");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ExternalLeagueId", "Season")
                        .IsUnique();

                    b.ToTable("tournaments", (string)null);
                });

            modelBuilder.Entity("Tip4Gen.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Auth0Sub")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("auth0_sub");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.HasKey("Id");

                    b.HasIndex("Auth0Sub")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Tip4Gen.Domain.Tipping.LongTermTip", b =>
                {
                    b.HasOne("Tip4Gen.Domain.Tournaments.NationalTeam", null)
                        .WithMany()
                        .HasForeignKey("TargetTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tip4Gen.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tip4Gen.Domain.Tipping.Tip", b =>
                {
                    b.HasOne("Tip4Gen.Domain.Tournaments.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tip4Gen.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tip4Gen.Domain.Tournaments.Match", b =>
                {
                    b.HasOne("Tip4Gen.Domain.Tournaments.NationalTeam", null)
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tip4Gen.Domain.Tournaments.NationalTeam", null)
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tip4Gen.Domain.Tournaments.Tournament", null)
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
